name: rescate_workspace
environment:
  sdk: ^3.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  record_linux: ^1.3.0
  archive: ^4.0.7

workspace:
  - apps/rescate_app
  - packages/ai_inference
  - packages/audio_voice
  - packages/biometric_estimators
  - packages/bluetooth_mesh
  - packages/dev_profiler
  - packages/offline_data
  - packages/security_crypto
  - packages/sensor_availability
