// Parity + unit tests for rag_v3 (Dart port of the validated Python pipeline).
//
// The fixtures (fixture_vectors_q8.bin / fixture_sentences.json /
// fixture_expected.json) are generated by eval/grading/make_fixtures.py from
// the live 7,535-sentence index: a 64-sentence slice with precomputed query
// embeddings and the Python pipeline's expected rankings.
//
// The numb-hand regression test locks in the red-flag behavior that
// motivated the triage layer.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:ai_inference/src/rag/rag_assets.dart';
import 'package:ai_inference/src/rag/rag_v3.dart';
import 'package:ai_inference/src/rag/red_flag_triage.dart';
import 'package:flutter_test/flutter_test.dart';

const _fixtureDir = 'test/rag_fixtures';

RagAssets _loadAssets() {
  final sentences = (jsonDecode(
    File('$_fixtureDir/fixture_sentences.json').readAsStringSync(),
  ) as List<dynamic>)
      .map((e) => RagSentence.fromJson(e as Map<String, dynamic>))
      .toList(growable: false);
  final vectors = RagVectors.fromBytes(
    File('$_fixtureDir/fixture_vectors_q8.bin').readAsBytesSync(),
  );
  expect(vectors.rows, sentences.length);
  return RagAssets(sentences: sentences, vectors: vectors);
}

Float32List _vecFromJson(List<dynamic> l) {
  final v = Float32List(l.length);
  for (var i = 0; i < l.length; i++) {
    v[i] = (l[i] as num).toDouble();
  }
  return v;
}

void main() {
  late RagAssets assets;

  setUpAll(() {
    assets = _loadAssets();
  });

  test('asset loader: fixture integrity', () {
    expect(assets.sentences.length, greaterThan(0));
    expect(assets.vectors.cols, 1024);
    expect(assets.vectors.data.length, assets.vectors.rows * 1024);
    expect(assets.vectors.scales.length, assets.vectors.rows);
    // every sentence must have non-empty text and a source
    for (final s in assets.sentences.take(10)) {
      expect(s.text, isNotEmpty);
      expect(s.source, isNotEmpty);
    }
  });

  test('rank: parity with Python pipeline (recorded expected order)', () {
    final expected =
        jsonDecode(File('$_fixtureDir/fixture_expected.json').readAsStringSync())
            as Map<String, dynamic>;
    final rag = RagV3(assets);
    for (final entry in expected['queries'] as List<dynamic>) {
      final e = entry as Map<String, dynamic>;
      final qv = _vecFromJson(e['query_vec'] as List<dynamic>);
      final hits = rag.rank(qv, topK: 8);
      final gotIds = hits.map((h) => h.sentence.id).toList();
      final wantIds = (e['expected_ids'] as List<dynamic>).cast<String>();
      // top-3 must match exactly; top-8 allow >=4 overlap (float jitter)
      expect(
        gotIds.take(3).toList(),
        wantIds.take(3).toList(),
        reason: 'query "${e['query']}" top-3 mismatch',
      );
      expect(
        gotIds.toSet().intersection(wantIds.toSet()).length,
        greaterThanOrEqualTo(4),
        reason: 'query "${e['query']}" top-8 overlap too low',
      );
    }
  });

  test('context builder: citation format + token budget', () {
    final expected =
        jsonDecode(File('$_fixtureDir/fixture_expected.json').readAsStringSync())
            as Map<String, dynamic>;
    final rag = RagV3(assets);
    final e = (expected['queries'] as List<dynamic>).first
        as Map<String, dynamic>;
    final qv = _vecFromJson(e['query_vec'] as List<dynamic>);
    final ctx = rag.buildContext(qv, topK: 8, maxTokens: 600, neighbors: 1);
    expect(ctx.context, isNot('NO_RELEVANT_CONTEXT'));
    expect(ctx.tokensEst, lessThanOrEqualTo(650));
    expect(ctx.context, contains('['));
    expect(ctx.sources, isNotEmpty);
  });

  test('neighbor expansion merges same-chunk siblings', () {
    final expected =
        jsonDecode(File('$_fixtureDir/fixture_expected.json').readAsStringSync())
            as Map<String, dynamic>;
    final rag = RagV3(assets);
    final e = (expected['queries'] as List<dynamic>).first
        as Map<String, dynamic>;
    final qv = _vecFromJson(e['query_vec'] as List<dynamic>);
    final expanded = rag.expandNeighbors(rag.rank(qv, topK: 4), neighbors: 1);
    // expanded texts must be >= base text lengths
    final base = rag.rank(qv, topK: 4);
    for (var i = 0; i < expanded.length; i++) {
      expect(expanded[i].sentence.text.length,
          greaterThanOrEqualTo(base[i].sentence.text.length));
    }
  });

  group('red-flag triage', () {
    test('numb-hand query fires stroke flag (regression anchor)', () {
      final hits = triageQuery('انا صحيت من النوم لقيت ايدي منملة و مش حاسس بيها');
      expect(hits.map((h) => h.flag.id), contains('stroke'));
    });

    test('arabic normalization: alef/ta-marbuta variants still match', () {
      expect(
        triageQuery('طفلي ابتلعت حبوب').map((h) => h.flag.id),
        contains('ingestion'),
      );
    });

    test('english phrasings fire their flags', () {
      expect(triageQuery('blood is soaking through the bandage')
          .map((h) => h.flag.id), contains('uncontrolled_bleeding'));
      expect(triageQuery("he can't breathe").map((h) => h.flag.id),
          contains('airway_breathing'));
      expect(triageQuery('my hand is burned and looks bad but doesnt hurt')
          .map((h) => h.flag.id), contains('severe_burn'));
    });

    test('benign queries produce no flags (no false positives)', () {
      expect(triageQuery('how do I treat a blister from hiking'), isEmpty);
      expect(triageQuery('what should be in a first aid kit'), isEmpty);
      expect(triageQuery('ازاي اعالج لسعة نحل بسيطة'), isEmpty);
    });

    test('escalation frame is produced per language', () {
      final hits = triageQuery('my dad is slurred and one side is weak');
      final en = escalationFrame(hits, false);
      expect(en, contains('TRIAGE ALERT'));
      expect(en, contains('STROKE'));
      final ar = escalationFrame(hits, true);
      expect(ar, contains('تنبيه تريج'));
    });
  });
}
