name: security_crypto
description: Module 5 - Security & Cryptography (Ed25519, Curve25519, SQLCipher)
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  # Add cryptography, sqflite_sqlcipher dependencies here later

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

resolution: workspace

