name: rescate_app
description: Rescate Main Application containing the Feature-Based UI architecture.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Modular Packages (Local Dependencies)
  ai_inference:
    path: ../../packages/ai_inference
  audio_voice:
    path: ../../packages/audio_voice
  biometric_estimators:
    path: ../../packages/biometric_estimators
  offline_data:
    path: ../../packages/offline_data
  p2p_mesh:
    path: ../../packages/p2p_mesh
  security_crypto:
    path: ../../packages/security_crypto
  sensor_availability:
    path: ../../packages/sensor_availability

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

resolution: workspace

flutter:
  uses-material-design: true
