name: rescate_app
description: Rescate Main Application containing the Feature-Based UI architecture.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  lucide_icons: any
  google_fonts: ^6.2.1
  
  # Core Modular Packages (Local Dependencies)
  ai_inference:
    path: ../../packages/ai_inference
  audio_voice:
    path: ../../packages/audio_voice
  offline_data:
    path: ../../packages/offline_data
  p2p_mesh:
    path: ../../packages/p2p_mesh
  security_crypto:
    path: ../../packages/security_crypto
  flutter_animate: ^4.5.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  speech_to_text: ^7.3.0
  geolocator: ^14.0.2
  flutter_map_tile_caching: ^9.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

resolution: workspace

flutter:
  uses-material-design: true
  assets:
    - assets/
